name: flutter_clean_arch
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dio: ^5.0.3
  dev: ^1.0.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  mockito: ^5.3.2
  build_runner: ^2.3.3
  # modular_test: ^3.0.1

flutter:
  uses-material-design: true
